In [1]:
import numpy as np

#QUESTION 1

In [2]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#QUESTION 2

In [5]:
vector_range = np.arange(10, 50)
print(vector_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#QUESTION 3

In [6]:
matrix= np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#QUESTION 4

In [7]:
non_zero_indices = np.nonzero([1, 2, 0, 0, 4, 0])
print(non_zero_indices)

(array([0, 1, 4], dtype=int64),)


#QUESTION 5

In [9]:
random_array = np.random.rand(10, 10)
min_value = random_array.min()
max_value = random_array.max()
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

Minimum Value: 0.00028765699974531156
Maximum Value: 0.9952478726284232


#QUESTION 6

In [16]:
random_vector = np.random.rand(30)
mean_value = random_vector.mean()
print("Mean Value:", mean_value)

Mean Value: 0.43963830161997747
